### ISSUE TITLE
Multiple links to one course should have their direct-bookmark link change to plus/minus along with the clicked one

### ISSUE THREAD

**Issue by 75th** [75th/mario-maker-linker#12]
Now that you're keeping a cache of all levels linked on the page, this might not be too too hard? But I haven't looked into it yet.

I'm sorry all I do is post issues, I only get rare stolen moments to sit down and work on this.

**Comment by freundTech** [comment]
I already noticed that, but haven't started working on it yet.

Will look into it as soon as possible.

**Comment by freundTech** [comment]
Fixed
