### ISSUE TITLE
Error when installing chrome extension from Store

### ISSUE THREAD

**Issue by freundTech** [75th/mario-maker-linker#15]
When trying to install the Chrome extension from the Crome Web Store I get `Package is invalid. Details: 'Could not decode image: 'icon-48.png''.`

Version is 47.0.2526.106 (64-bit) on Linux.

**Comment by 75th** [comment]
Uploaded a new version to fix this. In my haste, I used OS X's default context-menu compression, which does not resolve symlinks. So the icon-48.png was a symlink to a place outside the fricking folder I zipped up. Won't make that mistake again.

I'll close this when it hits the Chrome Web Store and I confirm that it works.
