### ISSUE TITLE
Course IDs with nonstandard separators are not linked

### ISSUE THREAD

**Issue by 75th** [75th/mario-maker-linker#3]
Some people use spaces instead of hyphens. I'm a little hesitant to be liberal in what the script affects, because I don't want to mess up random hexadecimal strings in non-Mario Maker contexts. Maybe when the script/extension can configure what sites it runs on, this will be a better idea.

**Comment by 75th** [comment]
I think this works now, too, right? I really need a test file with all permutations of course IDs

**Comment by freundTech** [comment]
Yes. At the moment IDs seperated by "-" or " " (or a mixture of both) are detected.

Only coursed that exist are linked. Nonexistant course IDs are ignored.
( DC46-0000-00F7-3E0A will be a link, while DC47-0000-00F7-3E0A won't be.)

**Comment by freundTech** [comment]
Is a website whitelist still a planned feature or can this be closed by now?
