### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by freundTech** [75th/mario-maker-linker#6]
I've noticed that your repository doesn't contain a license file.

Have you already thought about what license you want to use?
(Github provides a usefull site here: http://choosealicense.com/)

I would suggest either the MIT License (People can do whatever they want as long as they give credit) or the LGPLv3 (If people use the code in their products they have to publish their products under the same license + give credit.)

**Comment by 75th** [comment]
Definitely want MIT. Just committed it, with an added disclaimer about Nintendo.
